name: schedule

on:
  schedule:
    - cron: "30 1/4 * * *"

jobs:
  check_and_update:
    uses: mafalda-sfu/workflows/.github/workflows/schedule.yml@v1

    with:
      reference-package-name: "@mafalda-sfu/mediasoup-node-tests"

      # Update
      dependencies-update-latest: "@mafalda-sfu/* mediasoup"

      # Docs
      destination-repository-name: Mafalda-SFU.github.io
      docs-coverage_gistID: ${{ vars.DOCS_COVERAGE_GISTID }}
      user-email: bot@mafalda.io
      user-name: Mafalda Bot

      # Publish GitHub Packages Registry
      gpr-npm-version_gistID: ${{ vars.GPR_NPM_VERSION_GISTID }}

    secrets:
      GIST_SECRET: ${{ secrets.GIST_SECRET }}
      npm_token: ${{ secrets.npm_token }}
      SSH_DEPLOY_KEY: ${{ secrets.SSH_DEPLOY_KEY }}
      SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
